// <auto-generated />
using System;
using FleksProfitAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FleksProfitAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("FleksProfitAPI.Models.FcrRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("FCRabroad_MW")
                        .HasColumnType("REAL");

                    b.Property<double?>("FCRcross_DKK")
                        .HasColumnType("REAL");

                    b.Property<double?>("FCRcross_EUR")
                        .HasColumnType("REAL");

                    b.Property<double?>("FCRdk_DKK")
                        .HasColumnType("REAL");

                    b.Property<double?>("FCRdk_EUR")
                        .HasColumnType("REAL");

                    b.Property<double?>("FCRdomestic_MW")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("HourDK")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("HourUTC")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HourUTC")
                        .IsUnique();

                    b.ToTable("FcrRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
