<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include=".github\workflows\dotnet-tests.yml" />
  </ItemGroup>

  <ItemGroup>
    <!-- Runtime-only dependencies -->
    <PackageReference Include="Npgsql" Version="8.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />

    <PackageReference Include="net-questdb-client" Version="3.0.1" />
  </ItemGroup>
</Project>
